<template>
  <Layout>
    <p class="italic font-normal bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-semibold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-bold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <!-- <p class="italic font-normal bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-semibold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-bold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-normal bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-semibold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-bold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-normal bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-semibold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-bold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-normal bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-semibold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-bold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-normal bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-semibold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-bold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-normal bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-semibold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-bold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-normal bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-semibold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-bold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-normal bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-semibold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-bold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p>
    <p class="italic font-extrabold bg-red-500 font-nunito-sans">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus hic consectetur aut dolore, sunt odit nihil ut illo cum voluptas expedita quod harum consequatur ad doloremque natus obcaecati aspernatur similique.</p> -->
  </Layout>
</template>

<script>
export default {
  metaInfo: {
    title: 'Portfolio'
  }
}
</script>
